// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY7JPVUNIEUbswM-XSr6L6C4SReXOtfBk',
    appId: '1:296395952975:web:7f6d4085a7da37bd69ab3a',
    messagingSenderId: '296395952975',
    projectId: 'voyage-57d3e',
    authDomain: 'voyage-57d3e.firebaseapp.com',
    storageBucket: 'voyage-57d3e.appspot.com',
    measurementId: 'G-0GW3008LEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh7gnT3tOzsr-uQASC4JT8UxV62fPygkI',
    appId: '1:296395952975:android:513f5c06ac24857c69ab3a',
    messagingSenderId: '296395952975',
    projectId: 'voyage-57d3e',
    storageBucket: 'voyage-57d3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDInHWERtWSURBz5xP056zLOfapD9urxSY',
    appId: '1:296395952975:ios:14da9bba0d63875969ab3a',
    messagingSenderId: '296395952975',
    projectId: 'voyage-57d3e',
    storageBucket: 'voyage-57d3e.appspot.com',
    iosClientId: '296395952975-drulo1jtnsmkvujsdm7t224d2m88ju6t.apps.googleusercontent.com',
    iosBundleId: 'com.gazala.voyage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY7JPVUNIEUbswM-XSr6L6C4SReXOtfBk',
    appId: '1:296395952975:web:7994d05de00f423669ab3a',
    messagingSenderId: '296395952975',
    projectId: 'voyage-57d3e',
    authDomain: 'voyage-57d3e.firebaseapp.com',
    storageBucket: 'voyage-57d3e.appspot.com',
    measurementId: 'G-SCE3GBBFNP',
  );
}
